### ISSUE TITLE
Issue in publishing to Blogger.com

### ISSUE THREAD

**Issue by abhaymin** [Flamenco/stackeditpro#10]
Hi, reporting a bug here.

I am trying to publish a content to blogger.com, but I am getting an error "HTTP error 403." and in the dev-console on chrome browser

"Blogger API v3 has not been used in project 828035657739 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/blogger.googleapis.com/overview?project=828035657739 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

![image](https://user-images.githubusercontent.com/3757227/155857021-e07a6477-6429-48cd-9f98-9b8f93c11233.png)

**Comment by Flamenco** [comment]
Hello @abhaymin,

You are the first to use Blogger.  We can certainly enable it in Google.   I just followed the link and enabled it.  Can you please confirm it worked?

**Comment by abhaymin** [comment]
@Flamenco, yes the blogger connection error is gone. 

Thank you for letting me know, that I am the first to test this 😎 👍 . this issue is resolved.

Though there are lot of noise in the console logs been recorded, attached here is the log file.
[stackeditpro.io-1645957208775.log](https://github.com/Flamenco/stackeditpro/files/8148474/stackeditpro.io-1645957208775.log)

May be linked with issue #9

**Comment by Flamenco** [comment]
Thanks @abhaymin.  That log issue was already reported as you noted.
