### ISSUE TITLE
How to refresh folder tree?

### ISSUE THREAD

**Issue by hoclun-rigsep** [Flamenco/stackeditpro#12]
If someone added a file upstream how do I get it to show up in the folder tree?

**Comment by hoclun-rigsep** [comment]
Wait, does it only show `*.md`? I'm working with a couple of `*.mmd` (mermaid) files. GitHub recognizes the extension and renders the diagrams. If necessary I could rename the file to `.md` and wrap contents in ` ```mermaid``` `

**Comment by Flamenco** [comment]
Yes, it only shows .md files.

**Comment by Flamenco** [comment]
I think wrapping would be best, as the downstream parser is not equipped to simply open file types other than markdown.
