### ISSUE TITLE
C Sharp highlight doesn’t work

### ISSUE THREAD

**Issue by Ashechol** [Flamenco/stackeditpro#13]
![E2C664A1-39CB-470B-A573-118913409FD8](https://user-images.githubusercontent.com/34626395/162377680-9e7b982d-83e9-4e93-a3d5-39604ce50b97.jpeg)

**Comment by Flamenco** [comment]
Yes, @Ashechol, C# is not in the build.  We will post a new version ASAP.

<img width="406" alt="Screen Shot 2022-04-09 at 2 31 17 PM" src="https://user-images.githubusercontent.com/819940/162587170-e9fc4d6f-4583-4256-8b6e-bc8fc53ce13d.png">

**Comment by Flamenco** [comment]
Updated in version v1.0.0-beta.21

** Use `csharp` as fence name **

<img width="623" alt="Screen Shot 2022-04-09 at 10 29 25 PM" src="https://user-images.githubusercontent.com/819940/162598596-42a38079-1bf6-4a8b-8bdd-78e45dccd080.png">

**Comment by Ashechol** [comment]
Thanks a lot
