### ISSUE TITLE
StackEditPro cruft complicates rebase workflow

### ISSUE THREAD

**Issue by hoclun-rigsep** [Flamenco/stackeditpro#18]
I have to review my authors' work but when I skip commits during a rebase I get conflicts because of SEP's trailing comment. Anyone have any ideas how to smooth this out?

**Comment by Flamenco** [comment]
This is an implementation from upstream, so best to ask there.

@hoclun-rigsep 
If the comment is metadata, can't you just merge it in?

**Comment by hoclun-rigsep** [comment]
Yes but not automatically. If I rebase a series of commits made with SEP but skip some of the commits, git's patch algo doesn't (can't) resolve automatically. 
--

**Comment by Flamenco** [comment]
It seems like a limitation of the upstream, so I am going to close this as "out of our jurisdiction".

**Comment by hoclun-rigsep** [comment]
Yes it is a limitation of upstream and even if it weren't you'd have to change the way this cruft is stored in order to do anything about it from within this code. However: upstream is dead. Users of SEP may want to know what your plan/policy is for actionable issues that are "upstream" going forward.

**Comment by Flamenco** [comment]
Understood, but as we have started using a different product in-house,  we have continued to renew our SSL certificate and provide a host server as a convenience and goodwill to the community.

If this were an app breaking issue, we would possibly dedicate the resources to look into an upstream issue.  We would also integrate a PR if it was submitted to the upstream project, even though they are not active.

In your case, the issue just means more commits in GIT.  Not really app breaking.  From the start of this project, we have clearly stated that we add features, fix major bugs, provide a host, and do not charge a fee for the service.

**Comment by hoclun-rigsep** [comment]
Understood—I find all of what you say here reasonable.

**Comment by Flamenco** [comment]
As much as we like StackEdit, there were some major design issues that made the project too difficult to continue extending.  

We ended up creating a project that employs real-time collaborative editing, and replaces the folder tree for organizing documents with a much more flexible solution.

Perhaps it will be released to the public one of these days.
