### ISSUE TITLE
Certificate expired July 10th

### ISSUE THREAD

**Issue by stupacshakur** [Flamenco/stackeditpro#6]
![2021-07-12 07_59_58-Window](https://user-images.githubusercontent.com/11128682/125310187-39cd2300-e2e7-11eb-8e47-23e127e79810.png)

**Comment by Flamenco** [comment]
@stupacshakur We will be updating this ASAP. Thanks.

**Comment by Flamenco** [comment]
Oh, we already did. Closing...
