### ISSUE TITLE
Git auth needs updating

### ISSUE THREAD

**Issue by hoclun-rigsep** [Flamenco/stackeditpro#8]
https://github.com/benweet/stackedit/pull/1724

**Comment by Flamenco** [comment]
@hoclun-rigsep Thank you. We will look into this ASAP.

**Comment by hoclun-rigsep** [comment]
Guys this looks like a tiny fix and I bet you would win many permanent converts if you merged it and deployed it. I'm not the only one with a StackEdit-based workflow I had to design for normies that is now dead in the water.

**Comment by Flamenco** [comment]
We identified the issue and are releasing the patch in 1.0.0-beta.20.

**Comment by Flamenco** [comment]
@hoclun-rigsep please confirm this work for you.

**Comment by hoclun-rigsep** [comment]
I confirm.
