### ISSUE TITLE
CORS error on app load

### ISSUE THREAD

**Issue by hoclun-rigsep** [Flamenco/stackeditpro#9]
Chromium on linux:

```
Access to XMLHttpRequest at 'https://www.twelvetone.tv/api/usage' from origin 'https://stackeditpro.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I am logged into github but I've just reset the app (with the "Reset App" menu item.) This comes up right away.

**Comment by Flamenco** [comment]
@hoclun-rigsep  Thanks.  Might be a certificate issue.  Does the app still function?

**Comment by hoclun-rigsep** [comment]
Yes, the app functions. I don't think I would have noticed if I weren't investigating another "bug" (I misspelled a github repository leading to 404 from the github API).

**Comment by Flamenco** [comment]
Great.  It just means we are not getting usage analytics, so some might consider that a feature!  We will backlog this for a bit, as fixing it might break other stuff.

Thanks for the report.

**Comment by Flamenco** [comment]
@hoclun-rigsep Please confirm this issue is fixed, so we can close it.  Thanks!

**Comment by hoclun-rigsep** [comment]
Confirmed; requests to twelvetone.tv appear to succeed and no CORS error shows up in console.
